on: 
  push:
    branches:    
      - 'main'
    paths:
      - '.github/workflows/deployTest.yml'
name: AzureARMDeployTest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: github-what-the-hack-rg
        template: ./ARM-Templates/container-webapp-template.json